language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q Django==$DJANGO_VERSION django-appconf>=1.0.1
script: python runtests.py
