language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO="Django<1.8,>1.7"
  - DJANGO="Django<1.9,>1.8"
install:
  - pip install -q $DJANGO django-appconf>=1.0.1
script: python runtests.py
